import { Employee } from '../model';

export const mockEmployees: Employee[] = [
  {
    id: 91720,
    nationality: 'PL',
    keycardId: '52122b5f-2a8b-4506-b880-aac5e86d7d72',
    account: 'PL92 0200 9442 0911 9006 6507 9046',
    salary: 9628,
    office: ['Lublin', 'Poland'],
    departmentId: 4,
    firstName: 'Bertram',
    lastName: 'Kruszewski',
    title: 'Junior .Net Engineer',
    contractType: 'contract',
    email: 'Bertram66@softix.com',
    hiredAt: '2007-08-14',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 51,
      phone: '1-390-798-9734 x32319',
      email: 'Bertram.Kruszewski@gmail.com',
      address: {
        street: '5222 Orin Inlet',
        city: 'Colleen port',
        country: 'Sri Lanka',
      },
      dateOfBirth: '1967-09-06',
    },
    skills: ['DDD', 'MVC', 'data structures', 'algorithms', 'scrum', 'testing'],
    bio: 'Aliquid et consequatur est explicabo et suscipit.\nNumquam dicta nihil rem.\nDoloribus inventore molestiae voluptates dolorum repellat architecto exercitationem unde tempora.\nAlias cum nulla ea maiores commodi odit praesentium eum omnis.\nUt consequatur ut.\n \rId et consequatur minus a.\nUllam repellat laudantium voluptatem est veritatis et qui deleniti.\nItaque eum minus voluptas ut.\nTempore praesentium voluptas et.\nVoluptas voluptatem ducimus voluptates ut.\nMagnam laborum maxime expedita veniam atque quo ducimus animi.\n \rCupiditate aspernatur odio officia nulla rerum.\nRem quod doloremque nisi in suscipit vitae eligendi.\nVel deserunt hic ratione itaque ab ipsum qui cupiditate voluptas.\nSunt pariatur quia ut.',
    imgURL: 'nurse-white-male.png',
  },
  {
    id: 2684786,
    nationality: 'US',
    keycardId: 'af0413e9-e004-4a5f-80c5-44360c24971d',
    account: 'US09 3087 8646 4505 9622 6837',
    salary: 9374,
    office: ['Dallas', 'United States of America'],
    departmentId: 5,
    firstName: 'John',
    lastName: 'Herzog',
    title: 'Principal .Net Developer',
    contractType: 'contract',
    email: 'John2@softix.com',
    hiredAt: '2006-01-04',
    expiresAt: '2018-10-29',
    personalInfo: {
      age: 56,
      phone: '(900) 623-6763 x901',
      email: 'John_Herzog@yahoo.com',
      address: {
        street: '613 Yasmin Plaza',
        city: 'Brenden ville',
        country: 'Slovakia (Slovak Republic)',
      },
      dateOfBirth: '1962-07-23',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'TypeScript',
      'jQuery',
      'HTML',
    ],
    bio: 'Quas quaerat doloribus eaque deserunt eius amet saepe occaecati ducimus.\nEst sunt vitae sit omnis asperiores dolores sit et.\nEius dolores aut ut sunt aperiam ab fugiat.\nUt velit exercitationem aliquid architecto et.\nQuo consectetur voluptas illo quidem dicta.\n \rEaque porro quo maxime aspernatur esse hic doloribus.\nExcepturi quasi voluptates est.\nNam voluptas suscipit autem cupiditate est iste a qui.\nEt expedita quidem.\nQuaerat odit quia.\n \rPorro itaque nihil.\nSed qui dolor officia vel inventore aut dolorem hic exercitationem.\nDeleniti qui in odio a hic.',
    imgURL: 'scuba-diver-black-male.png',
  },
  {
    id: 9484463,
    nationality: 'PL',
    keycardId: '18a903a6-f5f8-47c1-85d9-5f5b6b335ada',
    account: 'PL39 8014 6064 8700 4003 0624 7105',
    salary: 9971,
    office: ['Gdańsk', 'Poland'],
    departmentId: 5,
    firstName: 'Leila',
    lastName: 'Szeląg',
    title: 'Principal Software Developer',
    contractType: 'permanent',
    email: 'Leila71@softix.com',
    hiredAt: '2011-07-06',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 44,
      phone: '(822) 489-4740 x127',
      email: 'Leila78@yahoo.com',
      address: {
        street: '93123 Monahan Trail',
        city: 'West Clinton ville',
        country: 'Latvia',
      },
      dateOfBirth: '1974-07-10',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'TypeScript',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Alias ipsum perferendis temporibus distinctio.\nVoluptate iure et est ea autem.\nA ex unde suscipit eos nesciunt.\n \rAssumenda autem dignissimos aliquam ipsam et neque.\nModi nostrum sit.\nDebitis ipsum recusandae porro quos quia ea vel nihil.\nUt sequi voluptatem aperiam ut.\nPraesentium dolorem sequi dolor laboriosam dolor temporibus vel.\n \rEsse amet adipisci accusamus dolores non deserunt libero corrupti.\nQuo ab aut atque numquam vel eos ad neque repellendus.\nNeque culpa impedit.',
    imgURL: 'young-hippies-black-female.png',
  },
  {
    id: 557954,
    nationality: 'IT',
    keycardId: 'dbcd1c40-8d8d-4382-ac9a-085de4906c82',
    account: 'IT75 T566 9725 0306 S144 7819 818',
    salary: 4787,
    office: ['Torino', 'Italy'],
    departmentId: 3,
    firstName: 'Jacopo',
    lastName: 'Costa',
    title: '.Net Developer',
    contractType: 'permanent',
    email: 'Jacopo51@softix.it',
    hiredAt: '1997-11-06',
    expiresAt: '2018-03-19',
    personalInfo: {
      age: 49,
      phone: '1-371-233-6052',
      email: 'Jacopo33@yahoo.com',
      address: {
        street: '3659 Haley Forks',
        city: 'Howell chester',
        country: 'Tanzania',
      },
      dateOfBirth: '1969-06-25',
    },
    skills: [
      'JavaScript',
      'react',
      'redux',
      'jQuery',
      'HTML',
      'algorithms',
      'scrum',
      'testing',
    ],
    bio: 'Qui impedit iusto molestiae.\nHic cumque mollitia est voluptatem praesentium enim est.\nCumque et deleniti quo.\nIure molestiae dolor.\nUt eum ut.\nSoluta eum veritatis.\n \rCumque est magnam dolores.\nEt excepturi eligendi quam eum ipsa minima recusandae.\nEst ratione aut debitis voluptates.\nQuaerat est blanditiis asperiores ut sequi vero.\n \rQuo voluptatum voluptas.\nVelit qui non ut aperiam ea quia sit.\nInventore culpa enim eos nisi dolorum eos aut eveniet.\nVoluptates minima deserunt omnis eum aspernatur.',
    imgURL: 'average-people-white-male.png',
  },
  {
    id: 65797404,
    nationality: 'IT',
    keycardId: 'e405f0c1-7c13-4713-b350-30292f8228ea',
    account: 'IT62 K786 6605 9171 0758 07Y7 Q4G',
    salary: 1570,
    office: ['Roma', 'Italy'],
    departmentId: 1,
    firstName: 'Matteo',
    lastName: 'Martino',
    title: 'Junior .Net Developer',
    contractType: 'contract',
    email: 'mama@softix.it',
    hiredAt: '1998-07-31',
    expiresAt: '2017-12-09',
    personalInfo: {
      age: 34,
      phone: '(656) 901-7634',
      email: 'Matteo52@hotmail.com',
      address: {
        street: '486 Keshawn Lakes',
        city: 'North Oran berg',
        country: 'Ethiopia',
      },
      dateOfBirth: '1984-03-15',
    },
    skills: [
      'JavaScript',
      'redux',
      'AngularJS',
      'jQuery',
      'HTML',
      'data structures',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Et distinctio dolores.\nCulpa repellat eum sapiente sit id.\nQuo modi hic velit sed distinctio ipsum.\nHic vel assumenda nisi iusto illum voluptatum.\nQui sunt et unde fugit veritatis est.\nTotam animi eum possimus molestias.\n \rIncidunt maxime et aut dolores distinctio est molestiae.\nQuisquam dolor consequatur doloribus veniam aut nihil.\nRem dignissimos nihil et eligendi ipsam laudantium minima nobis.\n \rUnde doloremque repellendus vel quaerat.\nAut quos molestias voluptas dolores voluptas et dolorum.\nEt eum est dolores veniam tempore non.\nIpsam ex ab similique voluptatem possimus.\nSint fuga quia excepturi.',
    imgURL: 'hipsters-asian-male.png',
  },
  {
    id: 190385,
    nationality: 'ES',
    keycardId: '6b7d78c4-677b-4d97-89ba-5faeb1e01495',
    account: 'ES36 2606 7555 0710 0794 6107',
    salary: 1197,
    office: ['Madrid', 'Spain'],
    departmentId: 6,
    firstName: 'Conchita',
    lastName: 'Granados',
    title: 'Senior .Net Engineer',
    contractType: 'contract',
    email: 'Conchita_Granados88@softix.es',
    hiredAt: '2009-01-21',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 32,
      phone: '933.374.9538',
      email: 'Conchita_Granados30@gmail.com',
      address: {
        street: '9664 Hodkiewicz Stravenue',
        city: 'North Kennedy land',
        country: 'Equatorial Guinea',
      },
      dateOfBirth: '1986-11-26',
    },
    skills: [
      'Java',
      'scala',
      'JavaScript',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'algorithms',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Illo vitae ratione facilis qui in rerum ducimus rem.\nUt impedit quo voluptates laudantium accusamus est reprehenderit.\nDolores velit commodi molestiae eaque.\nAmet ut corporis dolorem aspernatur et facilis minima ducimus.\nEx nihil ad magnam in.\nNecessitatibus molestias molestiae assumenda.\n \rEst est sed.\nQuia aut quos.\nConsectetur animi ut commodi.\nAccusamus aut ut quisquam.\nDebitis pariatur iusto.\n \rAperiam asperiores accusantium ab.\nSoluta repellendus magnam animi omnis perferendis fugit rerum aliquam nesciunt.\nDolorem eum aliquam perferendis ullam.\nTemporibus aut id ut qui eveniet earum quisquam amet nemo.',
    imgURL: 'celebrity-matrix-niobe.png',
  },
  {
    id: 85339,
    nationality: 'DE',
    keycardId: 'ece94784-f44c-4037-83a6-e3d3ac27bb42',
    account: 'DE60 4040 0691 1000 5043 72',
    salary: 2901,
    office: ['Frankfurt am Main', 'Germany'],
    departmentId: 1,
    firstName: 'Dorothea',
    lastName: 'Biesenbach',
    title: 'Junior Big Data Developer',
    contractType: 'permanent',
    email: 'dobi@softix.de',
    hiredAt: '2005-12-01',
    expiresAt: '2017-09-15',
    personalInfo: {
      age: 61,
      phone: '833.855.5464',
      email: 'Dorothea_Biesenbach@gmail.com',
      address: {
        street: '37700 Rashad Harbors',
        city: 'Buckridge land',
        country: 'Guernsey',
      },
      dateOfBirth: '1957-05-06',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'AngularJS',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
      'scrum',
      'testing',
    ],
    bio: 'Odit non fugiat et voluptas autem magni.\nMolestiae id fugiat dolores animi aliquid.\nProvident reprehenderit nobis possimus.\nAnimi aspernatur magni suscipit.\nEx perferendis aut quia veniam.\nCulpa ut sunt incidunt voluptas similique.\n \rDolor assumenda ut.\nPraesentium magnam autem nulla fugit est quae.\nUllam voluptatibus tempore culpa modi beatae voluptas dolor.\nSed ratione architecto occaecati necessitatibus et vero velit aut ipsum.\n \rOmnis consequatur vitae ut quae aspernatur iste sint quidem.\nConsequuntur quia est perferendis ex nulla atque quia laboriosam labore.\nMaiores deleniti repudiandae exercitationem voluptatem totam non id iure.\nTemporibus enim nisi nesciunt et provident placeat architecto officia libero.',
    imgURL: 'young-hippies-black-female.png',
  },
  {
    id: 5118488,
    nationality: 'DE',
    keycardId: 'bca1b53a-19fd-41e9-84fb-33b47cf469e5',
    account: 'DE87 6017 3926 0028 1844 81',
    salary: 2933,
    office: ['München', 'Germany'],
    departmentId: 2,
    firstName: 'Amy',
    lastName: 'Lenzen',
    title: 'Software Engineer',
    contractType: 'contract',
    email: 'Amy65@softix.de',
    hiredAt: '1998-06-30',
    expiresAt: '2018-04-07',
    personalInfo: {
      age: 58,
      phone: '718-070-4373',
      email: 'Amy_Lenzen32@gmail.com',
      address: {
        street: '212 Rau Way',
        city: 'Lake Pinkie',
        country: 'Samoa',
      },
      dateOfBirth: '1960-03-27',
    },
    skills: [
      'C#',
      '.net',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'react',
      'Angular',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Quo eveniet et laudantium est aut quis possimus aut.\nNesciunt impedit accusantium.\nIpsum sit repellendus autem eos explicabo consequuntur commodi nostrum.\n \rQuis vel voluptate aut voluptates officia molestias aperiam.\nTempora ut ab rerum blanditiis velit consectetur voluptatibus ut rerum.\nAut animi ea non nostrum aut omnis recusandae.\n \rConsequatur est tenetur atque optio distinctio.\nVoluptatem placeat in quae et voluptas quis illo.\nImpedit optio beatae nostrum distinctio quos doloribus aut a.\nDolor consequuntur debitis aliquid ea.',
    imgURL: 'nurse-white-male.png',
  },
  {
    id: 155156,
    nationality: 'PL',
    keycardId: 'e13fa20c-8f01-4677-b557-3f5079419c49',
    account: 'PL70 0039 0461 1243 0014 0002 5446',
    salary: 4457,
    office: ['Radom', 'Poland'],
    departmentId: 7,
    firstName: 'Agrypina',
    lastName: 'Czapla',
    title: 'Software Engineer',
    contractType: 'contract',
    email: 'Agrypina.Czapla@softix.pl',
    hiredAt: '2011-09-29',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 43,
      phone: '234-762-9944 x41413',
      email: 'Agrypina29@hotmail.com',
      address: {
        street: '257 Boyer Station',
        city: 'Port Caden view',
        country: 'Guyana',
      },
      dateOfBirth: '1975-08-13',
    },
    skills: [
      'SOA',
      'MVC',
      'Scalability',
      'Java',
      'JVM',
      'spring',
      'Hibernate',
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'sql',
    ],
    bio: 'Aut repellat commodi.\nIn ut reprehenderit exercitationem rerum qui non tempore.\nSunt vero quas quo blanditiis rem tempora debitis.\nNobis necessitatibus sit.\nEst dolorem quo vel officiis qui.\n \rAmet aut eos nihil aspernatur est.\nRepellat aut deserunt.\nRerum molestiae ut tempore et iusto totam.\nQuia dolorem sit ratione illo nihil.\nNemo non perspiciatis possimus minima nostrum.\n \rDolorum tenetur et dolorem aut assumenda.\nQuis doloremque cum alias.\nIpsa consequatur quae ut soluta.\nEveniet voluptas rerum unde enim perferendis eius excepturi eligendi.',
    imgURL: 'punk-black-female.png',
  },
  {
    id: 5488446,
    nationality: 'UK',
    keycardId: '57269ad4-bab2-4b27-9291-fa59762d8c65',
    account: 'GB51 GWAI 8102 0871 0449 15',
    salary: 6520,
    office: ['London', 'United Kingdom'],
    departmentId: 2,
    firstName: 'Etha',
    lastName: 'Braun',
    title: 'Senior .Net Engineer',
    contractType: 'permanent',
    email: 'Etha_Braun68@softix.uk',
    hiredAt: '2011-10-17',
    expiresAt: '2018-08-24',
    personalInfo: {
      age: 32,
      phone: '682.086.5484',
      email: 'Etha.Braun98@gmail.com',
      address: {
        street: '8986 Yasmin Plain',
        city: 'Romaguera ton',
        country: 'Tajikistan',
      },
      dateOfBirth: '1986-10-29',
    },
    skills: [
      'Java',
      'spring',
      'JSP',
      'Hibernate',
      'JavaScript',
      'CSS',
      'HTML',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Culpa dolorum dicta praesentium in est soluta eum repellendus magnam.\nIn esse eos qui cumque.\nImpedit minus eveniet natus illum.\nVel labore aut aliquid.\nDoloribus quis voluptas illum quo.\nDucimus excepturi natus nulla sit ipsam dolor enim et eveniet.\n \rAliquid voluptates non error consequatur ut et fugit.\nEa odio veniam aliquid earum animi sed neque in natus.\nAliquid tempora quaerat sint architecto similique doloribus quasi.\nRepellendus unde quia hic nihil.\n \rSunt suscipit magnam ut neque.\nQuas consequatur qui nulla.\nSint quisquam eos et.',
    imgURL: 'military-general-asian-female.png',
  },
  {
    id: 2183,
    nationality: 'PL',
    keycardId: 'aacdb833-f442-45fe-87fb-d5c85401d375',
    account: 'PL69 0087 4090 7003 3005 3095 6009',
    salary: 1718,
    office: ['Wrocław', 'Poland'],
    departmentId: 6,
    firstName: 'Greta',
    lastName: 'Zając',
    title: 'Software Engineer',
    contractType: 'permanent',
    email: 'grza@softix.pl',
    hiredAt: '2006-01-04',
    expiresAt: '2018-08-15',
    personalInfo: {
      age: 29,
      phone: '1-583-018-1424 x4546',
      email: 'Greta79@hotmail.com',
      address: {
        street: '796 Stuart Coves',
        city: 'West Blanche',
        country: 'Cape Verde',
      },
      dateOfBirth: '1989-04-12',
    },
    skills: [
      'Java',
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'scrum',
    ],
    bio: 'Vero sint repellat excepturi dicta consequatur.\nConsequatur quidem et voluptas sit quia itaque.\nVeritatis magnam animi cum dolorum ut enim officia deleniti.\nIpsum voluptatem ducimus laudantium eos.\nIn est reprehenderit.\n \rSaepe expedita aut.\nLaborum et est sit dolorum repellendus.\nQuia accusantium dolor aut asperiores qui.\nRerum exercitationem cum corrupti consequatur aut deserunt illo.\n \rDistinctio ut dignissimos provident sed et.\nUt aut non ex provident.\nAd quisquam ab aspernatur eum libero illum aliquam et nisi.',
    imgURL: 'doctor-black-female.png',
  },
  {
    id: 22601476,
    nationality: 'US',
    keycardId: '8718e650-42f5-4d73-86cc-5b79a40239a9',
    account: 'US85 1400 1009 1910 0752 0700',
    salary: 4747,
    office: ['Dallas', 'United States of America'],
    departmentId: 2,
    firstName: 'Rodrigo',
    lastName: 'Ebert',
    title: 'Senior Software Developer',
    contractType: 'contract',
    email: 'roeb@softix.com',
    hiredAt: '2012-11-23',
    expiresAt: '2018-09-19',
    personalInfo: {
      age: 43,
      phone: '285.692.5780 x37920',
      email: 'Rodrigo80@hotmail.com',
      address: {
        street: '867 Tomasa Circle',
        city: 'Gleichner port',
        country: 'Gibraltar',
      },
      dateOfBirth: '1975-12-23',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'VisualStudio',
      'JavaScript',
      'react',
      'redux',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Fugit autem omnis dolores.\nFacilis optio suscipit et sint.\nVel est labore aut corporis sit ut quo.\nNecessitatibus dolores unde.\nEst consequuntur impedit inventore est explicabo consectetur qui.\nImpedit odio laudantium qui inventore sunt praesentium harum.\n \rQuibusdam qui voluptatem ut laudantium commodi velit.\nAut quod accusamus illum et est voluptas consectetur deserunt nesciunt.\nDicta velit rem et quisquam.\nEst ex dolorum porro magni possimus labore optio ab.\n \rEos omnis nobis incidunt autem aspernatur voluptas quaerat repudiandae vitae.\nAspernatur eos corporis magni.\nAliquid commodi perspiciatis in ex ullam et animi.\nNeque est illum nemo hic et.\nEnim aspernatur quas qui ut autem earum.\nVeritatis eum est quos dolorem aut id hic enim.',
    imgURL: 'celebrity-matrix-niobe.png',
  },
  {
    id: 447819,
    nationality: 'US',
    keycardId: 'e1ff702b-2ae1-4dcc-bece-4f2d27b62532',
    account: 'US75 9407 0038 6200 8200 4005',
    salary: 5064,
    office: ['San Francisco', 'United States of America'],
    departmentId: 2,
    firstName: 'Erik',
    lastName: 'Senger',
    title: 'Junior Big Data Engineer',
    contractType: 'contract',
    email: 'erse@softix.com',
    hiredAt: '1996-08-20',
    expiresAt: '2018-09-23',
    personalInfo: {
      age: 24,
      phone: '023.656.0346',
      email: 'Erik95@gmail.com',
      address: {
        street: '45227 Ernestina Valleys',
        city: 'East Jacey',
        country: 'Vietnam',
      },
      dateOfBirth: '1994-10-22',
    },
    skills: ['Java', 'JVM', 'spring', 'JSP', 'Hibernate', 'sql', 'SQL Server'],
    bio: 'Sit cumque perferendis voluptatem et ratione dolor dolor odit.\nLabore magnam rerum.\nConsequatur labore velit aut esse fugiat ut aut voluptatem.\nEarum qui consequatur unde qui a error incidunt porro cum.\nArchitecto corrupti veniam quisquam enim qui ipsam sit blanditiis consequuntur.\nPerspiciatis ipsum rem explicabo dignissimos id numquam cupiditate.\n \rUllam qui et assumenda.\nPerspiciatis magni tenetur optio sit quae nobis.\nHic quis adipisci et qui fugiat rerum molestiae.\nVoluptatem et aut et quis dolorem.\nEaque omnis culpa dicta sunt dolore dolorem dolores.\nIllum voluptatem nihil provident ullam quo vitae deserunt.\n \rAccusantium et ut doloremque molestiae a.\nQuis voluptatem id.\nVoluptatem sequi aliquam quia.',
    imgURL: 'superhero-black-panther-comics.png',
  },
  {
    id: 29916839,
    nationality: 'UK',
    keycardId: '2395f77c-5e51-45db-ad48-c592c8ea2ef3',
    account: 'GB77 OXBQ 0070 4400 7156 05',
    salary: 4904,
    office: ['Manchester', 'United Kingdom'],
    departmentId: 7,
    firstName: 'Ferne',
    lastName: 'Denesik',
    title: 'Junior .Net Engineer',
    contractType: 'permanent',
    email: 'fede@softix.com',
    hiredAt: '2002-09-27',
    expiresAt: '2019-01-21',
    personalInfo: {
      age: 24,
      phone: '1-067-993-5828 x18738',
      email: 'Ferne28@hotmail.com',
      address: {
        street: '554 Javier Trail',
        city: 'Ratke chester',
        country: 'Palau',
      },
      dateOfBirth: '1994-09-06',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'AngularJS',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
      'SOA',
      'MVC',
      'Security',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Iusto fugit quo incidunt sit quis quos impedit totam fugiat.\nQuis sed dolores voluptatibus autem omnis.\nDeleniti aut quia voluptas et tempore voluptatem voluptate aut molestiae.\n \rConsequatur facilis et vero et incidunt error et voluptas ipsum.\nPlaceat quam ut.\nFacilis nisi officia quod et illo nihil.\n \rDoloremque quod alias voluptas enim quibusdam omnis beatae et.\nNostrum ex temporibus eum quia rerum voluptatibus similique dolore assumenda.\nVitae nostrum et non.\nVelit sunt vero ut et sit rerum dolorum accusantium.\nFacere debitis labore.',
    imgURL: 'hip-hop-black-male.png',
  },
  {
    id: 2613485,
    nationality: 'US',
    keycardId: '17e0adaf-fc0f-4b20-a440-60e9b13c5519',
    account: 'US55 0900 9009 0560 0830 8899',
    salary: 7692,
    office: ['San Francisco', 'United States of America'],
    departmentId: 2,
    firstName: 'Elody',
    lastName: 'Kohler',
    title: 'Software Developer',
    contractType: 'contract',
    email: 'Elody_Kohler@softix.us',
    hiredAt: '2004-10-31',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 60,
      phone: '523-830-7303',
      email: 'Elody_Kohler@hotmail.com',
      address: {
        street: '0394 Ocie Parks',
        city: 'South Pietro land',
        country: 'Pakistan',
      },
      dateOfBirth: '1958-10-29',
    },
    skills: [
      'DDD',
      'SOA',
      'MVC',
      'Scalability',
      'Security',
      'Java',
      'scala',
      'JVM',
      'spring',
      'JSP',
      'C#',
      '.net',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'sql',
    ],
    bio: 'Eum sed quia sunt impedit aut sit.\nConsequatur dolore et commodi minima illo debitis sit a saepe.\nConsequatur rerum cum error.\nVoluptatem incidunt reprehenderit perspiciatis veritatis deserunt.\nCupiditate porro reprehenderit eos voluptatem deleniti sit.\nDolores repellat vel dicta similique.\n \rEt aperiam in.\nSapiente dicta qui officia iste sint.\nAspernatur corporis voluptatem.\nImpedit aut repellendus est placeat earum natus.\nNatus eius tempora asperiores consequatur.\n \rCorporis quis voluptatibus et recusandae est.\nVoluptates et amet labore beatae non.\nIusto voluptas doloribus eum.\nIncidunt at optio quod odit in enim magni.\nNihil excepturi porro iste veniam necessitatibus molestiae tempore ut in.\nMolestiae sit ut nesciunt.',
    imgURL: 'bandit-white-male-cowboy.png',
  },
  {
    id: 828648,
    nationality: 'PL',
    keycardId: 'bb25aba5-9a70-4dcf-97a5-0c10a5705d5c',
    account: 'PL80 0910 0394 7009 5007 8878 1988',
    salary: 9961,
    office: ['Łódź', 'Poland'],
    departmentId: 7,
    firstName: 'Roman',
    lastName: 'Buczkowski',
    title: 'Java Developer',
    contractType: 'contract',
    email: 'robu@softix.pl',
    hiredAt: '2004-05-30',
    expiresAt: '2018-09-09',
    personalInfo: {
      age: 24,
      phone: '564-694-7716',
      email: 'Roman.Buczkowski@yahoo.com',
      address: {
        street: '164 Linnea Pines',
        city: 'Francesco shire',
        country: 'Hong Kong',
      },
      dateOfBirth: '1994-12-20',
    },
    skills: [
      'Java',
      'scala',
      'JVM',
      'JSP',
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'data structures',
      'algorithms',
      'scrum',
      'testing',
    ],
    bio: 'Eos et sed.\nVoluptatum ipsum corrupti dolorum ut ratione et.\nDignissimos qui adipisci et pariatur consequatur officia illum expedita mollitia.\nFuga amet dolor quia ipsam minima.\nIllo perspiciatis officia autem aspernatur.\n \rVoluptates et dolore consequatur cum accusantium doloribus.\nRepellat corrupti corporis repellendus tenetur molestias ratione ut praesentium.\nSed laboriosam aut ut delectus et.\nDolor velit sunt corrupti provident animi maiores.\nEt nihil voluptate est laudantium autem et.\nIllum alias molestias repellat ab amet incidunt.\n \rOptio velit id et ut quo est.\nOfficiis ut sint et modi itaque quo pariatur sint.\nEa temporibus perspiciatis accusamus id voluptate facere qui enim.',
    imgURL: 'disc-jockey-black-male.png',
  },
  {
    id: 79800965,
    nationality: 'PL',
    keycardId: '419a5a33-a60e-4188-a8c6-1d1012cffa18',
    account: 'PL18 0020 1284 0082 0248 9008 8002',
    salary: 6241,
    office: ['Łódź', 'Poland'],
    departmentId: 5,
    firstName: 'Władysław',
    lastName: 'Olejniczak',
    title: 'Junior .Net Developer',
    contractType: 'permanent',
    email: 'Wadysaw45@softix.com',
    hiredAt: '1999-01-02',
    expiresAt: '2019-04-05',
    personalInfo: {
      age: 37,
      phone: '319-227-9052 x198',
      email: 'Wadysaw.Olejniczak16@gmail.com',
      address: {
        street: '793 Kaden Plains',
        city: 'Kutch port',
        country: 'Palau',
      },
      dateOfBirth: '1981-10-29',
    },
    skills: [
      'Java',
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'scrum',
      'testing',
    ],
    bio: 'Non quis officia ea.\nUt quibusdam provident consequatur aut libero quia quaerat ea.\nFacere unde est.\nHarum exercitationem quasi ipsa dolor.\n \rEsse impedit distinctio aliquid nesciunt consequatur ut ut.\nMagni enim non.\nTotam amet esse non ut ea commodi.\nRepellendus suscipit in eum sed accusamus ab perspiciatis dolores voluptatem.\nCommodi voluptate sed eius voluptatibus necessitatibus impedit quos.\n \rNostrum distinctio sint autem facere iusto labore.\nReiciendis harum ea excepturi minima nemo autem exercitationem.\nQui reiciendis quo voluptatem eum.',
    imgURL: 'scuba-diver-black-male.png',
  },
  {
    id: 76510941,
    nationality: 'PL',
    keycardId: '292abd73-4498-489a-8123-b603182d7e24',
    account: 'PL92 3735 5902 7340 8787 0555 5605',
    salary: 6408,
    office: ['Łódź', 'Poland'],
    departmentId: 7,
    firstName: 'Ansgary',
    lastName: 'Ruciński',
    title: 'Junior .Net Engineer',
    contractType: 'contract',
    email: 'Ansgary34@softix.com',
    hiredAt: '2008-03-26',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 35,
      phone: '1-594-866-9667',
      email: 'Ansgary_Ruciski96@gmail.com',
      address: {
        street: '0568 Johnston Trace',
        city: 'Port Isabell burgh',
        country: 'Algeria',
      },
      dateOfBirth: '1983-10-17',
    },
    skills: [
      'SOA',
      'MVC',
      'Scalability',
      'Java',
      'JVM',
      'spring',
      'JSP',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'sql',
      'MongoDB',
      'neo4j',
      'Cassandra',
    ],
    bio: 'Qui accusamus nulla rerum eum dignissimos enim et excepturi.\nBeatae eum esse autem.\nEt quaerat magni facere reprehenderit qui qui sit.\nNon qui libero corporis voluptas esse.\nQuo est amet qui.\nQui voluptatum non dolorem et cumque.\n \rFacere praesentium adipisci voluptatibus temporibus.\nAsperiores alias quis aperiam numquam corporis corrupti ut ab.\nUnde fuga facilis et voluptatem repellendus ut est ducimus dolores.\nOccaecati quaerat exercitationem minus aliquid quibusdam ipsam illum.\nLibero dolor voluptatem.\n \rEt velit aut eos rerum illum nobis.\nQuo est sint non nihil qui et tempora qui odit.\nDolorem est est ut eius.',
    imgURL: 'french-beret-white-male.png',
  },
  {
    id: 561722,
    nationality: 'NL',
    keycardId: '7b2344be-e0b8-4beb-9b58-563866bad561',
    account: 'NL59 JNDV 3062 0060 87',
    salary: 9456,
    office: ['Utrecht', 'Netherlands'],
    departmentId: 7,
    firstName: 'Sander',
    lastName: 'Bruin',
    title: 'Junior Software Engineer',
    contractType: 'contract',
    email: 'sabr@softix.nl',
    hiredAt: '1996-10-31',
    expiresAt: '2018-05-04',
    personalInfo: {
      age: 46,
      phone: '046.351.4117',
      email: 'Sander53@yahoo.com',
      address: {
        street: '07403 Kutch Lock',
        city: 'West Bethel',
        country: 'Anguilla',
      },
      dateOfBirth: '1972-02-24',
    },
    skills: [
      'Java',
      'scala',
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'sql',
      'Oracle',
      'SQL Server',
      'MongoDB',
    ],
    bio: 'Odit vel facere.\nNemo et officia molestiae suscipit omnis.\nPraesentium quibusdam deleniti quia harum ratione omnis dolores distinctio rerum.\n \rAut aut quas cupiditate vel velit.\nPerferendis quod sed molestiae qui aliquid omnis aliquam quisquam voluptatem.\nEst est eos numquam aperiam sed consequatur natus.\nQui nihil ut consequatur.\nTotam voluptas sunt unde dicta quibusdam quo ut et officia.\nRepudiandae sunt praesentium occaecati corrupti sint natus cupiditate accusantium.\n \rIpsam commodi fuga omnis.\nUt excepturi sint quis magni quibusdam.\nCorporis explicabo est quam qui maiores.\nAut exercitationem corrupti omnis tempore.\nRepudiandae maxime iusto illum.',
    imgURL: 'punk-asian-male.png',
  },
  {
    id: 112531792,
    nationality: 'NL',
    keycardId: '2b4a235f-d5b8-45d3-b0e0-8c2d9ca58112',
    account: 'NL11 KXOZ 0600 8107 42',
    salary: 6694,
    office: ['Utrecht', 'Netherlands'],
    departmentId: 5,
    firstName: 'Lisa',
    lastName: 'Veen',
    title: 'Junior Software Developer',
    contractType: 'permanent',
    email: 'live@softix.nl',
    hiredAt: '2003-09-02',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 43,
      phone: '586.848.0855',
      email: 'Lisa.Veen@yahoo.com',
      address: {
        street: '2293 Greenholt Flat',
        city: 'Emard stad',
        country: 'Malta',
      },
      dateOfBirth: '1975-07-27',
    },
    skills: [
      'SOA',
      'MVC',
      'Scalability',
      'Java',
      'JVM',
      'spring',
      'Hibernate',
      'C#',
      '.net',
      'OData',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'sql',
      'Oracle',
    ],
    bio: 'Quo temporibus veritatis quidem.\nVelit ullam est odio.\nNeque molestias cupiditate odio vel.\n \rEveniet exercitationem doloribus ullam nostrum voluptatem.\nEt ullam natus.\nNisi unde voluptatem quos.\nQuos rerum esse veniam et qui voluptas.\nOmnis et non atque ipsum molestias amet illum.\nIste natus iusto animi ab et ut.\n \rTempora autem mollitia.\nAutem consequatur quisquam id dolorem.\nAd et excepturi ut quisquam.\nVero quaerat ab soluta iure.\nRem rerum et nostrum iste quibusdam culpa quo quas cumque.',
    imgURL: 'civil-rights-gandhi.png',
  },
  {
    id: 556391,
    nationality: 'PL',
    keycardId: '68525e4b-8bf4-4c3b-a0d8-751dc54cc75f',
    account: 'PL92 0030 0960 0803 0309 0789 0032',
    salary: 8610,
    office: ['Gdańsk', 'Poland'],
    departmentId: 4,
    firstName: 'Mikołaj',
    lastName: 'Sochacki',
    title: 'Principal Java Engineer',
    contractType: 'contract',
    email: 'miso@softix.com',
    hiredAt: '2010-05-04',
    expiresAt: '2018-03-08',
    personalInfo: {
      age: 62,
      phone: '081-262-6352 x884',
      email: 'Mikoaj.Sochacki@yahoo.com',
      address: {
        street: '83940 Santino Springs',
        city: 'Abdiel fort',
        country: 'Chile',
      },
      dateOfBirth: '1956-12-10',
    },
    skills: [
      'JavaScript',
      'jQuery',
      'CSS',
      'HTML',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Odit dicta non maxime et vel cumque.\nMolestiae officiis accusantium et.\nSed dolores beatae.\nDolor itaque est eveniet sed doloremque deleniti esse minima incidunt.\nReprehenderit cumque eos distinctio possimus enim.\nId accusamus ut facilis possimus a consectetur adipisci aut totam.\n \rEos ducimus earum facilis libero id nobis quo magnam odit.\nQuis beatae soluta magnam fuga amet ratione veniam.\nDignissimos non dolorem est qui quibusdam ut minus pariatur asperiores.\nQuia eum qui dolor consequatur aspernatur itaque cumque magni impedit.\n \rSed sint qui enim.\nDicta ea eum.\nIn aut quisquam aut occaecati culpa odit.',
    imgURL: 'traditional-attire-native-male.png',
  },
  {
    id: 4239369,
    nationality: 'US',
    keycardId: 'cfb66b5b-199b-4a18-96a9-65c3d8d856fe',
    account: 'US48 6108 7055 4204 4004 3008',
    salary: 2358,
    office: ['San Francisco', 'United States of America'],
    departmentId: 5,
    firstName: 'Carmelo',
    lastName: 'Kris',
    title: 'Senior Java Engineer',
    contractType: 'contract',
    email: 'cakr@softix.com',
    hiredAt: '2000-12-01',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 23,
      phone: '195-501-0370',
      email: 'Carmelo_Kris80@gmail.com',
      address: {
        street: '103 Yasmine Turnpike',
        city: 'East Rosalind furt',
        country: 'Saint Vincent and the Grenadines',
      },
      dateOfBirth: '1995-06-12',
    },
    skills: [
      'MVC',
      'Security',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'scrum',
    ],
    bio: 'Et molestias consequatur eos.\nDolor atque sequi fugit enim aut eos cum alias.\nUt est aut sit culpa.\nIpsa consequatur aut neque.\nMinus dolorum consequatur.\n \rQuia sit ea esse similique voluptas.\nSequi vel est consequatur fugit iste a facere eos nam.\nIusto sapiente dolorem dolores a odit esse molestiae sit vero.\nAliquid possimus omnis et praesentium dicta.\nSuscipit quia amet placeat porro tempora dolorem sunt ipsam consequuntur.\nEt officia qui dolorem est debitis quia doloribus.\n \rQui aut vero possimus et doloribus facilis molestiae quasi velit.\nUllam cumque eum ut a autem.\nOdit qui molestiae odio aut.\nAperiam odit sit itaque et aliquid et aut.',
    imgURL: 'graduates-black-male.png',
  },
  {
    id: 523121864,
    nationality: 'PL',
    keycardId: '9832c005-b86f-4fac-bfd5-76e39c35b30a',
    account: 'PL35 1095 7006 1040 2504 0768 9972',
    salary: 2980,
    office: ['Łódź', 'Poland'],
    departmentId: 3,
    firstName: 'Stanisław',
    lastName: 'Mikulski',
    title: 'Big Data Developer',
    contractType: 'contract',
    email: 'Stanisaw.Mikulski33@softix.pl',
    hiredAt: '2000-11-20',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 39,
      phone: '1-522-747-1104',
      email: 'Stanisaw_Mikulski@hotmail.com',
      address: {
        street: '650 Jake Row',
        city: 'Lake Jeromy',
        country: 'Benin',
      },
      dateOfBirth: '1979-07-28',
    },
    skills: ['marketing', 'digital marketing', 'social media'],
    bio: 'Eum rerum quasi ut.\nEst accusamus ut et.\nFugiat quos quae.\nIn eius qui quaerat temporibus.\n \rDolorem sed aliquid vero cupiditate aut laudantium aut quia odio.\nTempore nemo consectetur eum voluptatem aut rerum omnis.\nEius rem et voluptatem quaerat facilis iusto alias.\n \rUt consequatur eius repellat quis consectetur qui vel.\nExplicabo consequatur nobis eos aspernatur qui.\nVeniam odio deleniti tempora ullam quisquam itaque ut.\nVoluptatem maxime eveniet quibusdam quia quas commodi molestias.\nTempore nesciunt voluptatibus repudiandae iure harum.',
    imgURL: 'french-beret-white-male.png',
  },
  {
    id: 46767,
    nationality: 'NL',
    keycardId: '6d6c5a9c-215f-4626-b794-233645256992',
    account: 'NL95 EQDE 4400 1000 83',
    salary: 7470,
    office: ['Amsterdam', 'Netherlands'],
    departmentId: 1,
    firstName: 'Ruben',
    lastName: 'Smits',
    title: '.Net Engineer',
    contractType: 'permanent',
    email: 'rusm@softix.nl',
    hiredAt: '2007-07-20',
    expiresAt: '2017-12-30',
    personalInfo: {
      age: 37,
      phone: '1-097-722-0796',
      email: 'Ruben68@hotmail.com',
      address: {
        street: '947 Ellen Shoals',
        city: 'Twila land',
        country: 'Saint Lucia',
      },
      dateOfBirth: '1981-03-30',
    },
    skills: [
      'SOA',
      'MVC',
      'Scalability',
      'Java',
      'JVM',
      'spring',
      'JSP',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'sql',
      'Cassandra',
    ],
    bio: 'Tenetur saepe autem consequatur ut non laborum quis ea.\nVoluptas quia molestiae pariatur doloribus ut repellendus itaque at impedit.\nDistinctio exercitationem et nesciunt voluptas dolor repellendus voluptatem.\n \rIn dolorem fugit voluptas sed voluptas quibusdam recusandae nisi temporibus.\nItaque facere libero est exercitationem.\nExcepturi mollitia et maxime eius optio harum.\nNesciunt eos quia earum magni modi assumenda molestias quis.\n \rVero dolorem aspernatur quae impedit non saepe in.\nSoluta laborum incidunt quisquam minus modi.\nOptio eos modi.\nEnim voluptatem aut eius dignissimos et ea error quibusdam porro.\nCupiditate sint quo ex omnis dolores minus qui alias.',
    imgURL: 'surgeon-black-male.png',
  },
  {
    id: 98943,
    nationality: 'ES',
    keycardId: 'b9b13cbc-5a84-4a50-8143-6b96903a1697',
    account: 'ES75 0090 0402 1209 0212 5365',
    salary: 9390,
    office: ['Madrid', 'Spain'],
    departmentId: 5,
    firstName: 'Josefina',
    lastName: 'Olivares',
    title: 'Senior .Net Developer',
    contractType: 'contract',
    email: 'Josefina_Olivares30@softix.com',
    hiredAt: '2004-06-27',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 45,
      phone: '871.924.7885 x03793',
      email: 'Josefina.Olivares@hotmail.com',
      address: {
        street: '23018 Adams Gateway',
        city: 'Krystal chester',
        country: 'Lesotho',
      },
      dateOfBirth: '1973-01-06',
    },
    skills: [
      'C#',
      '.net',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'redux',
      'Angular',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Inventore totam eum est iste non.\nQuo ex et natus.\nMinus eveniet aut.\n \rNisi omnis et animi in quisquam laudantium porro libero nobis.\nDolorum magnam et.\nQuia unde eos voluptas quis.\nTempore qui libero quis ullam exercitationem.\nVoluptas eos blanditiis cupiditate et.\n \rIpsum vitae consequatur explicabo ea autem maiores aliquid ducimus pariatur.\nDolores ex ea velit nam et.\nSit itaque quo.\nProvident sit hic consequatur itaque.\nSed eos et tempore doloremque cumque et.',
    imgURL: 'senior-citizens-white-female.png',
  },
  {
    id: 8201204,
    nationality: 'DE',
    keycardId: '00fa9a10-ab4a-438f-929d-f4b98edec6e9',
    account: 'DE91 0047 9064 0035 0090 84',
    salary: 4902,
    office: ['München', 'Germany'],
    departmentId: 2,
    firstName: 'Georg',
    lastName: 'Mesloh',
    title: 'Junior Java Developer',
    contractType: 'permanent',
    email: 'Georg_Mesloh59@softix.de',
    hiredAt: '2005-04-10',
    expiresAt: '2019-05-02',
    personalInfo: {
      age: 38,
      phone: '(220) 802-3606 x87687',
      email: 'Georg50@yahoo.com',
      address: {
        street: '062 Hudson Corners',
        city: 'Ilene town',
        country: 'Panama',
      },
      dateOfBirth: '1980-02-27',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'TypeScript',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Quia fugit sed possimus qui qui atque illum.\nMaxime omnis atque quisquam adipisci aut ut aut recusandae quam.\nSed eos cupiditate facere.\nAut architecto quos perferendis minima quibusdam voluptatem porro minus.\n \rEaque aut delectus velit.\nDelectus numquam blanditiis non quo iste.\nQuo non quia quibusdam.\nDolor ducimus reprehenderit.\nRepellendus ducimus cum dolores praesentium officiis hic vero eveniet.\nExplicabo earum ea atque.\n \rUt ea adipisci autem molestiae tempore eos at pariatur.\nQuia earum quibusdam quas officiis non iure.\nRerum non libero neque.\nPariatur eius ea illum fugiat similique.',
    imgURL: 'military-general-black-male.png',
  },
  {
    id: 19714065,
    nationality: 'ES',
    keycardId: '0180e5c4-377e-406b-858f-d3a61ef326d8',
    account: 'ES69 8175 0450 2240 0108 1422',
    salary: 3720,
    office: ['Madrid', 'Spain'],
    departmentId: 1,
    firstName: 'Luis Miguel',
    lastName: 'Salcedo',
    title: 'Junior Java Developer',
    contractType: 'permanent',
    email: 'lusa@softix.es',
    hiredAt: '1998-01-29',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 47,
      phone: '274-572-8633',
      email: 'LuisMiguel56@yahoo.com',
      address: {
        street: '99918 Florence Wells',
        city: 'Botsford haven',
        country: 'Iraq',
      },
      dateOfBirth: '1971-12-26',
    },
    skills: ['customer support'],
    bio: 'Atque aut quis nihil ex minus itaque magni possimus.\nNisi sed fugiat ex nihil deserunt id.\nMolestias ullam expedita est qui ipsam dolore saepe architecto.\nUt adipisci aspernatur qui minima incidunt est quis.\nSapiente quas quasi facilis perspiciatis et sequi.\n \rExcepturi quos et repellat ullam.\nFacere eum qui dolor ducimus ut rerum.\nQui in maxime dicta.\nEa voluptas ipsum magnam placeat reprehenderit.\n \rUt ut eos ipsum sequi at omnis optio.\nPlaceat id labore.\nSit deleniti ut vero ab velit in quia dolor explicabo.\nA et quaerat.\nQuis et facilis est dolorem quo sed aliquam.',
    imgURL: 'hipsters-asian-male.png',
  },
  {
    id: 192931,
    nationality: 'UK',
    keycardId: '5f12c909-eb1d-4454-b776-d7f1207081ec',
    account: 'GB35 MAMG 2609 5070 4600 83',
    salary: 9993,
    office: ['Manchester', 'United Kingdom'],
    departmentId: 6,
    firstName: 'Fritz',
    lastName: 'Corwin',
    title: 'Java Engineer',
    contractType: 'permanent',
    email: 'Fritz.Corwin@softix.com',
    hiredAt: '2003-08-28',
    expiresAt: '2019-06-20',
    personalInfo: {
      age: 49,
      phone: '355.592.6492',
      email: 'Fritz78@yahoo.com',
      address: {
        street: '09759 Chester Crest',
        city: 'South Arnoldo',
        country: 'Canada',
      },
      dateOfBirth: '1969-10-25',
    },
    skills: [
      'Java',
      'JVM',
      'spring',
      'Hibernate',
      'TypeScript',
      'redux',
      'Angular',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'algorithms',
      'scrum',
    ],
    bio: 'Debitis iure quia voluptatibus est aut id ab.\nVoluptas autem et provident.\nOmnis quia aut officiis ex voluptatem.\nEsse omnis accusamus ipsa repellat laudantium fuga sapiente animi.\nQuia aliquid earum qui ipsam dolore et libero eos.\n \rExercitationem sed qui numquam quaerat ipsam ut minima veritatis.\nVel qui repudiandae porro rem voluptatem molestias magni odit.\nQui sed temporibus occaecati qui est odio quo quam.\n \rUllam perspiciatis recusandae quos tempore praesentium quibusdam.\nAb possimus ducimus voluptatum et.\nAb amet quo sapiente voluptatum totam.',
    imgURL: 'punk-asian-male.png',
  },
  {
    id: 29831,
    nationality: 'DE',
    keycardId: '871443c8-806c-4de6-bf34-ec41a9fb1053',
    account: 'DE30 7008 0279 0706 8687 85',
    salary: 8250,
    office: ['Frankfurt am Main', 'Germany'],
    departmentId: 3,
    firstName: 'Amira',
    lastName: 'Einert',
    title: 'Senior Java Engineer',
    contractType: 'permanent',
    email: 'Amira34@softix.com',
    hiredAt: '1993-03-12',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 64,
      phone: '(392) 637-5822',
      email: 'Amira.Einert@gmail.com',
      address: {
        street: '012 Jaskolski Port',
        city: 'New Elizabeth side',
        country: 'Uruguay',
      },
      dateOfBirth: '1954-12-14',
    },
    skills: [
      'SOA',
      'MVC',
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'data structures',
      'algorithms',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Quas ipsam tempore reprehenderit et placeat totam.\nFugit quis ea velit numquam magni blanditiis quo molestiae dolorem.\nDistinctio dicta porro voluptatem quibusdam itaque consequatur dolorem.\nVoluptatem cupiditate dolorem vitae.\nAt voluptas debitis aut laboriosam dolore.\n \rMaiores quasi hic velit odit id modi non.\nRecusandae eligendi sint dolorem vitae dolor.\nModi voluptatum pariatur nesciunt sapiente et dolor.\nAmet minima non adipisci vel.\n \rEos voluptatem at reprehenderit voluptas saepe natus soluta atque.\nSoluta quaerat consequuntur quo porro accusantium voluptas animi recusandae.\nPlaceat voluptas id consequatur enim sed unde sequi voluptas corporis.',
    imgURL: 'celebrity-magritte-apple-boler.png',
  },
  {
    id: 73064,
    nationality: 'US',
    keycardId: '0dc31cf2-5bbe-4587-a0a1-126623b00378',
    account: 'US10 0755 5520 4930 0830 5631',
    salary: 5567,
    office: ['San Francisco', 'United States of America'],
    departmentId: 5,
    firstName: 'Clemens',
    lastName: 'Trantow',
    title: 'Big Data Developer',
    contractType: 'permanent',
    email: 'cltr@softix.us',
    hiredAt: '2006-03-13',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 35,
      phone: '729-370-4291',
      email: 'Clemens.Trantow@hotmail.com',
      address: {
        street: '268 Mills Inlet',
        city: 'Bernier stad',
        country: 'Virgin Islands, British',
      },
      dateOfBirth: '1983-04-04',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'Rx.net',
      'VisualStudio',
      'JavaScript',
      'CoffeeScript',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Itaque occaecati suscipit et maiores atque et numquam aliquam blanditiis.\nRepellendus sit in libero amet corporis.\nPossimus inventore ad.\n \rExcepturi sunt repudiandae quia voluptatem repellendus.\nNecessitatibus magni aliquid autem quia.\nVoluptas praesentium et enim adipisci ea ipsam incidunt voluptatem et.\nQui eveniet ut sint doloremque voluptas.\nPariatur earum non distinctio aut dicta quas quaerat.\n \rRecusandae facilis impedit totam autem eaque nihil cumque maxime.\nAut magnam a eos tenetur iure ut.\nQui unde omnis quis possimus enim.\nExercitationem quo quis dolores modi officia et sapiente.',
    imgURL: 'average-people-black-male.png',
  },
  {
    id: 7042851,
    nationality: 'FR',
    keycardId: 'f37b18c2-5d8a-4065-aac0-e73c84510079',
    account: 'FR13 0036 9197 2240 4TKI 92CX 441',
    salary: 2108,
    office: ['Paris', 'France'],
    departmentId: 1,
    firstName: 'Zoe',
    lastName: 'Prevost',
    title: 'Big Data Developer',
    contractType: 'contract',
    email: 'zopr@softix.com',
    hiredAt: '1996-11-09',
    expiresAt: '2018-10-26',
    personalInfo: {
      age: 51,
      phone: '1-275-073-0399 x830',
      email: 'Zoe.Prevost22@yahoo.com',
      address: {
        street: '934 Bechtelar Junctions',
        city: 'New Talon port',
        country: 'Zambia',
      },
      dateOfBirth: '1967-08-04',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'TypeScript',
      'Angular',
      'AngularJS',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Deleniti aut pariatur consequatur aliquid nesciunt.\nSint sunt error tempora eius ut non.\nModi maxime in est rem eum.\nIncidunt dignissimos quia consequatur voluptas veniam qui aut deserunt et.\nDolorum non asperiores illum saepe alias pariatur placeat doloribus sequi.\nBeatae culpa ut deleniti et aut qui aut sed.\n \rUt deserunt dolorem nisi rerum molestias doloremque aliquam et beatae.\nNecessitatibus sint quos error quo accusamus veniam possimus.\nAccusantium corporis tenetur animi voluptatem magni id corrupti eum error.\nIste non quo magnam est et sunt nesciunt tenetur blanditiis.\nItaque aliquam et sit ad tenetur.\n \rCum voluptatem maxime et quidem earum voluptatem placeat ut.\nDignissimos nesciunt tenetur eaque dolore dolorem excepturi ea magni dolores.\nFacilis ad qui.',
    imgURL: 'scuba-diver-black-male.png',
  },
  {
    id: 982654355,
    nationality: 'DE',
    keycardId: 'd5d4d300-9857-4dea-88b1-66b3fcf38915',
    account: 'DE25 0200 6477 0466 1300 93',
    salary: 8372,
    office: ['Darmstadt', 'Germany'],
    departmentId: 3,
    firstName: 'Dario',
    lastName: 'Hentschke',
    title: 'Senior Java Engineer',
    contractType: 'contract',
    email: 'Dario39@softix.de',
    hiredAt: '1994-09-13',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 55,
      phone: '(801) 741-8003',
      email: 'Dario28@hotmail.com',
      address: {
        street: '164 Axel Track',
        city: 'North Buford fort',
        country: 'Malaysia',
      },
      dateOfBirth: '1963-12-29',
    },
    skills: [
      'JavaScript',
      'redux',
      'Angular',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'scrum',
      'testing',
    ],
    bio: 'Consequatur saepe quisquam similique molestiae.\nLaboriosam nesciunt qui sint sit aut nemo a.\nEst non dolores aut eum.\nSint corrupti perferendis sed dolores ipsum et.\nEst aspernatur sit nam.\n \rCupiditate et sed vero quia corporis.\nMolestiae occaecati nemo delectus praesentium id.\nNisi nihil aperiam.\nProvident iure qui possimus.\n \rEos asperiores tempora itaque quia accusamus tempore.\nTempore ab aut dicta praesentium quia et rerum nemo ut.\nFuga similique sed et.\nEos quia excepturi tenetur ipsam dicta voluptates repellat consequatur odio.\nOfficia et aut autem rerum qui nemo neque aut sunt.',
    imgURL: 'emo-black-male.png',
  },
  {
    id: 923647989,
    nationality: 'US',
    keycardId: '670e29a7-20b5-409c-adad-bb3b430a101d',
    account: 'US90 1020 8203 9202 1460 0974',
    salary: 6133,
    office: ['Dallas', 'United States of America'],
    departmentId: 2,
    firstName: 'Eriberto',
    lastName: 'Upton',
    title: 'Big Data Engineer',
    contractType: 'permanent',
    email: 'erup@softix.us',
    hiredAt: '1999-12-21',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 27,
      phone: '401-496-8865 x63636',
      email: 'Eriberto33@hotmail.com',
      address: {
        street: '218 Hildegard Overpass',
        city: 'Brakus land',
        country: 'Yemen',
      },
      dateOfBirth: '1991-03-26',
    },
    skills: [
      'SOA',
      'MVC',
      'Scalability',
      'Security',
      'Java',
      'spring',
      'JSP',
      'Hibernate',
      'C#',
      'F#',
      '.net',
      'IIS',
      'VisualStudio',
      'VSTS',
      'sql',
      'MongoDB',
    ],
    bio: 'Eum iusto sequi voluptatem.\nMolestiae sit dolorem.\nOfficia molestiae ut adipisci impedit deleniti voluptatem et sed.\nConsequatur consequuntur labore.\n \rQuidem maxime vel cupiditate ipsum esse dolor ut.\nAtque aut necessitatibus maiores.\nAut ratione dolorem sint nisi sit deleniti amet repellat.\nQui et eaque aut.\n \rEt veniam et aperiam.\nQuo ut cum et officia consequatur est possimus reiciendis ut.\nFacere rerum unde molestiae reiciendis.\nModi qui deleniti ut distinctio vel quaerat minus.\nAtque ipsam incidunt est deleniti provident perspiciatis.\nRepellat minus ex unde cum.',
    imgURL: 'young-hippies-white-male.png',
  },
  {
    id: 943123120,
    nationality: 'PL',
    keycardId: '71a033f9-c03b-40ac-942f-55d082a1f007',
    account: 'PL41 9050 1249 1981 0351 8794 0078',
    salary: 6856,
    office: ['Gdańsk', 'Poland'],
    departmentId: 5,
    firstName: 'Maurycy',
    lastName: 'Żurawski',
    title: 'Senior Java Engineer',
    contractType: 'contract',
    email: 'mażu@softix.com',
    hiredAt: '1995-06-16',
    expiresAt: '2017-11-17',
    personalInfo: {
      age: 29,
      phone: '509.644.3403 x5224',
      email: 'Maurycy_urawski26@hotmail.com',
      address: {
        street: '545 Dee Springs',
        city: 'Cormier side',
        country: 'Uganda',
      },
      dateOfBirth: '1989-03-13',
    },
    skills: [
      'Java',
      'scala',
      'JVM',
      'JSP',
      'Hibernate',
      'JavaScript',
      'react',
      'redux',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Omnis exercitationem iste ea optio tempora excepturi deserunt.\nQuos rem iste ab saepe asperiores ut.\nAssumenda natus vel esse ad est dolorem.\nUt quaerat in cum.\nDicta autem quidem aliquid tempore cum non quia eos.\nAut ducimus cum quia eos ipsam pariatur praesentium.\n \rEt dolor quos deserunt ipsa omnis quam doloribus ipsum aut.\nAut et ut.\nOmnis tenetur dolor laboriosam eveniet eum.\n \rQui ipsam a blanditiis.\nFugit quia necessitatibus dolores hic.\nQuos consequatur at ea odit optio officia qui veniam.\nSed alias enim ex voluptatum.\nDistinctio eos dolores et et voluptatum nostrum in recusandae a.',
    imgURL: 'construction-workers-white-male.png',
  },
  {
    id: 835032870,
    nationality: 'IT',
    keycardId: 'e3dfc26b-db1a-400e-9eb6-7374751ebdaa',
    account: 'IT14 S236 6798 628Q 1060 2D62 487',
    salary: 7802,
    office: ['Roma', 'Italy'],
    departmentId: 3,
    firstName: 'Giorgio',
    lastName: 'Barbieri',
    title: 'Junior Big Data Engineer',
    contractType: 'contract',
    email: 'Giorgio.Barbieri51@softix.com',
    hiredAt: '2009-04-08',
    expiresAt: '2018-03-24',
    personalInfo: {
      age: 64,
      phone: '058-151-9098 x9267',
      email: 'Giorgio_Barbieri@yahoo.com',
      address: {
        street: '330 Adolfo Ridges',
        city: 'East Lawson side',
        country: 'Philippines',
      },
      dateOfBirth: '1954-04-04',
    },
    skills: [
      'Java',
      'JVM',
      'Hibernate',
      'JavaScript',
      'CSS',
      'HTML',
      'scrum',
      'testing',
    ],
    bio: 'Id sit in blanditiis dolor iure et rerum molestiae est.\nVoluptatibus ea sit quam.\nVeniam similique ea praesentium molestias qui rerum id.\nDolorem saepe quidem minima alias praesentium fugit aspernatur et unde.\nSit ut quasi.\nAut et quos id quasi adipisci sint et inventore in.\n \rQui optio autem.\nVoluptas cumque possimus error.\nOfficiis rerum dignissimos illum.\nAd porro rerum consequatur perferendis sit voluptatibus officia.\nEveniet suscipit quis quo.\nIpsa sed accusamus.\n \rEos tempore ipsam perspiciatis.\nUnde modi aut.\nIste autem odit eos ab aut corrupti at.\nAutem expedita debitis qui.',
    imgURL: 'hipsters-asian-male.png',
  },
  {
    id: 984105710,
    nationality: 'US',
    keycardId: '0bc89e1b-74a1-4f69-abaf-1b1b18241d1b',
    account: 'US05 0144 7095 5364 4008 9252',
    salary: 4489,
    office: ['Dallas', 'United States of America'],
    departmentId: 3,
    firstName: 'Alice',
    lastName: 'Beer',
    title: 'Software Developer',
    contractType: 'permanent',
    email: 'albe@softix.us',
    hiredAt: '1994-03-07',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 45,
      phone: '1-122-449-3605 x18510',
      email: 'Alice_Beer@yahoo.com',
      address: {
        street: '079 Zachery Glens',
        city: 'Lake Millie',
        country: 'Somalia',
      },
      dateOfBirth: '1973-10-24',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'AngularJS',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Rerum occaecati soluta dolore sint velit et nam.\nIllo neque a vel et.\nDolorem maxime rerum non.\nEt quo iusto id veritatis voluptas aut inventore.\n \rNon qui quas repudiandae atque provident dolores.\nLaboriosam vel rerum voluptas hic.\nFacilis delectus mollitia nihil iure quo dolorum at voluptatem.\nEt odio ducimus.\nHarum quasi quia.\n \rQuas consectetur sit error ratione.\nEa maxime eligendi asperiores.\nCupiditate eius ut.\nDolor suscipit fugit deleniti velit assumenda eos et architecto occaecati.',
    imgURL: 'graduates-black-male.png',
  },
  {
    id: 1565579,
    nationality: 'IT',
    keycardId: '94326507-b402-46d5-96c1-d2522e558858',
    account: 'IT93 J059 0507 704U 3340 342L 910',
    salary: 2645,
    office: ['Torino', 'Italy'],
    departmentId: 1,
    firstName: 'Doriana',
    lastName: 'Barbieri',
    title: 'Senior .Net Developer',
    contractType: 'permanent',
    email: 'doba@softix.it',
    hiredAt: '2002-02-01',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 55,
      phone: '794.728.2772 x205',
      email: 'Doriana72@hotmail.com',
      address: {
        street: '0852 Halle Rue',
        city: 'Bartoletti chester',
        country: 'Virgin Islands, U.S.',
      },
      dateOfBirth: '1963-02-24',
    },
    skills: [
      'Java',
      'JVM',
      'JSP',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Alias hic suscipit repudiandae voluptatibus consequuntur et nobis maxime.\nQui qui autem illo soluta.\nConsequatur enim vero magni ipsam dolorem voluptatem qui.\nEa non totam.\n \rReiciendis eos vel.\nArchitecto minima nobis.\nEt vitae quia minima et doloremque reprehenderit molestias aut.\nRerum consectetur est non.\nIste cumque voluptatem consectetur maxime dolorem hic quas quo.\n \rAsperiores porro et perspiciatis tempore adipisci enim nemo fuga aut.\nCulpa et aut error blanditiis sint atque ut omnis.\nVelit doloribus tenetur non atque delectus dolorum blanditiis.\nMagni vel inventore aut.\nSunt qui quia aperiam eaque aspernatur magnam eveniet non deleniti.\nDoloribus ipsum vel sed quia sit molestias.',
    imgURL: 'traditional-attire-native-female.png',
  },
  {
    id: 675324973,
    nationality: 'DE',
    keycardId: 'c9b4d425-2dea-42d9-a3e2-cb8b837104f7',
    account: 'DE16 2500 8838 0901 0084 76',
    salary: 4439,
    office: ['Darmstadt', 'Germany'],
    departmentId: 2,
    firstName: 'Mark',
    lastName: 'Neuschwander',
    title: 'Software Developer',
    contractType: 'permanent',
    email: 'mane@softix.com',
    hiredAt: '2008-11-24',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 53,
      phone: '751.587.6031',
      email: 'Mark.Neuschwander8@yahoo.com',
      address: {
        street: '866 Blanda Underpass',
        city: 'Roman berg',
        country: 'Tanzania',
      },
      dateOfBirth: '1965-08-23',
    },
    skills: [
      'Java',
      'scala',
      'JSP',
      'JavaScript',
      'CoffeeScript',
      'AngularJS',
      'jQuery',
      'HTML',
    ],
    bio: 'Aut quos odio non id nam placeat dolores iste.\nQuia molestiae nemo quos.\nEa dolorum nihil consequuntur accusamus quis.\nVoluptatum voluptas consequatur architecto.\nA maiores quod natus vitae.\nMinima saepe quasi consectetur et facilis perspiciatis architecto magni id.\n \rTempore quia rerum recusandae.\nEst deleniti recusandae consequuntur omnis architecto et quae esse dolores.\nOdit eveniet et unde debitis.\nIn voluptatibus enim vel velit voluptates sint perspiciatis rerum.\nVoluptate voluptates aut dolor unde voluptatibus cupiditate iusto minus ipsa.\n \rMagni commodi debitis dolorum quia beatae quo et nihil.\nNisi deleniti quo.\nRatione consequatur in eum praesentium.',
    imgURL: 'big-beard-black-male.png',
  },
  {
    id: 59725859,
    nationality: 'US',
    keycardId: '7f73d9cc-1198-4ce6-8a14-a50dc2b380c1',
    account: 'US03 7006 0300 2113 5040 9148',
    salary: 4018,
    office: ['Dallas', 'United States of America'],
    departmentId: 6,
    firstName: 'Krystel',
    lastName: 'Ferry',
    title: 'Java Engineer',
    contractType: 'permanent',
    email: 'krfe@softix.us',
    hiredAt: '1999-08-24',
    expiresAt: '2019-04-08',
    personalInfo: {
      age: 44,
      phone: '1-294-738-0498 x0763',
      email: 'Krystel_Ferry98@yahoo.com',
      address: {
        street: '8622 Bauch Drive',
        city: 'Wyman berg',
        country: 'Antarctica (the territory South of 60 deg S)',
      },
      dateOfBirth: '1974-02-22',
    },
    skills: [
      'Java',
      'JVM',
      'Hibernate',
      'JavaScript',
      'TypeScript',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'algorithms',
      'scrum',
      'testing',
    ],
    bio: 'Sit alias totam eius consequatur sunt libero.\nExcepturi dolores omnis dolor aut repellendus qui aspernatur fugiat consequuntur.\nMollitia eveniet voluptas quam.\nDignissimos nam aut neque nemo dolores perferendis.\nNulla qui asperiores aut omnis ex quam voluptatem vel magnam.\n \rEt assumenda debitis maxime et eligendi dicta excepturi aut.\nVoluptatum impedit ea fuga.\nQuasi similique et odio dolor ut et repellat error sed.\n \rBlanditiis maiores quis ipsam repellat.\nMaxime ducimus et doloribus distinctio incidunt placeat autem ex.\nIllo eos nostrum quo.\nEt voluptas mollitia enim non excepturi accusantium illo ea.\nOdio maiores hic necessitatibus autem non ad tempora mollitia rerum.\nHic eveniet ut fugiat voluptas.',
    imgURL: 'nurse-white-male.png',
  },
  {
    id: 47370949,
    nationality: 'PL',
    keycardId: '04be912e-4366-454c-8457-4f36947c0116',
    account: 'PL40 6007 0990 0931 5980 9990 0329',
    salary: 6170,
    office: ['Lublin', 'Poland'],
    departmentId: 7,
    firstName: 'Bertrand',
    lastName: 'Cholewa',
    title: 'Big Data Developer',
    contractType: 'contract',
    email: 'bech@softix.com',
    hiredAt: '2011-06-29',
    expiresAt: '2018-06-19',
    personalInfo: {
      age: 54,
      phone: '1-657-159-2229 x6097',
      email: 'Bertrand1@hotmail.com',
      address: {
        street: '846 Towne Prairie',
        city: 'West Ottilie',
        country: 'Croatia',
      },
      dateOfBirth: '1964-04-14',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'react',
      'redux',
      'Angular',
      'AngularJS',
      'rxjs',
      'jQuery',
      'CSS',
      'HTML',
    ],
    bio: 'Ut quod eum suscipit architecto eos repudiandae.\nDeleniti atque non.\nNulla delectus provident.\nVelit sequi commodi sed soluta inventore quo.\n \rDolore ut quisquam nesciunt quis ut.\nEx nesciunt porro dolores.\nConsectetur deleniti animi quaerat ipsa ab ex.\nEx ut eveniet eos nobis doloribus dignissimos assumenda suscipit.\nEos consequatur dolores ad error laboriosam ratione eum cupiditate.\n \rUllam voluptates veritatis velit.\nSed aliquid rerum omnis et aut voluptatem natus.\nEligendi non iusto aut ipsa voluptatibus.\nDolorem blanditiis suscipit est ipsum ea enim et.\nAnimi quisquam repellendus.\nVoluptatem et magni itaque exercitationem nostrum omnis deserunt voluptatem suscipit.',
    imgURL: 'doctor-asian-male.png',
  },
  {
    id: 89254874,
    nationality: 'ES',
    keycardId: '9665be7c-17b1-493a-af48-dc8150f947a9',
    account: 'ES81 0002 0520 4903 0076 1800',
    salary: 1653,
    office: ['Madrid', 'Spain'],
    departmentId: 3,
    firstName: 'Fernando',
    lastName: 'Salgado',
    title: 'Senior Software Engineer',
    contractType: 'permanent',
    email: 'fesa@softix.es',
    hiredAt: '1993-02-27',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 33,
      phone: '455-316-8539 x789',
      email: 'Fernando.Salgado@yahoo.com',
      address: {
        street: '17602 Larkin Courts',
        city: 'New Perry haven',
        country: 'Kiribati',
      },
      dateOfBirth: '1985-06-25',
    },
    skills: [
      'Java',
      'scala',
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'VisualStudio',
      'data structures',
      'algorithms',
      'scrum',
      'testing',
    ],
    bio: 'Quaerat excepturi eos cupiditate sunt beatae repudiandae.\nAdipisci culpa nisi.\nSed aut suscipit quod accusantium qui libero qui.\nExcepturi qui aut sunt temporibus sed error ducimus.\nModi placeat omnis ut praesentium est rerum.\n \rAt quia quo ut tenetur aut nobis sint.\nSed omnis delectus inventore possimus.\nMolestiae reprehenderit dolorem iure voluptas.\n \rAccusantium est quibusdam et.\nNeque quos accusantium sequi enim consequatur cumque nesciunt.\nRerum est rerum officiis.',
    imgURL: 'french-beret-white-male.png',
  },
  {
    id: 2943879,
    nationality: 'ES',
    keycardId: '0e37d3fa-ea4b-46bd-90f9-7b61955c5b90',
    account: 'ES97 4983 3007 4260 0396 2924',
    salary: 2191,
    office: ['Madrid', 'Spain'],
    departmentId: 3,
    firstName: 'Carmen',
    lastName: 'Collazo',
    title: 'Big Data Developer',
    contractType: 'contract',
    email: 'caco@softix.com',
    hiredAt: '1995-03-24',
    expiresAt: '2019-03-17',
    personalInfo: {
      age: 31,
      phone: '(385) 925-2059 x877',
      email: 'Carmen81@yahoo.com',
      address: {
        street: '26358 Breitenberg Vista',
        city: 'Brandyn shire',
        country: 'Jamaica',
      },
      dateOfBirth: '1987-11-30',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'TypeScript',
      'jQuery',
      'CSS',
      'HTML',
      'SOA',
      'MVC',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Similique repudiandae earum in occaecati accusantium et ipsa.\nEt incidunt soluta et.\nRerum possimus nostrum voluptatum voluptatem itaque culpa.\n \rItaque quia sapiente expedita dolor esse ea sequi voluptatibus.\nQui amet quia est consequatur aperiam eligendi aspernatur rerum.\nCorporis placeat culpa voluptate numquam ab nam qui adipisci ut.\nQuis voluptas ut aut numquam a.\nMaxime est vel dignissimos qui enim.\n \rAb at qui.\nVoluptatem neque in et quia rerum consequatur similique itaque autem.\nEum non sunt dolorem est voluptas.',
    imgURL: 'hip-hop-black-male.png',
  },
  {
    id: 781470069,
    nationality: 'NL',
    keycardId: '10c800ac-afe5-4f9c-9345-253463e7206a',
    account: 'NL07 TKSO 6400 9904 01',
    salary: 5481,
    office: ['Den Haag', 'Netherlands'],
    departmentId: 5,
    firstName: 'Kevin',
    lastName: 'Jacobs',
    title: 'Senior Big Data Engineer',
    contractType: 'permanent',
    email: 'Kevin76@softix.com',
    hiredAt: '2009-06-04',
    expiresAt: '2018-06-20',
    personalInfo: {
      age: 51,
      phone: '194-285-6876 x07202',
      email: 'Kevin82@yahoo.com',
      address: {
        street: '4014 Joannie Underpass',
        city: 'South Kristian',
        country: 'Svalbard & Jan Mayen Islands',
      },
      dateOfBirth: '1967-09-23',
    },
    skills: [
      'SOA',
      'MVC',
      'Security',
      'Java',
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'C#',
      '.net',
      'EntityFramework',
      'IIS',
      'VisualStudio',
      'VSTS',
      'sql',
      'SQL Server',
      'MongoDB',
    ],
    bio: 'Corrupti reiciendis libero iste.\nLaboriosam repudiandae placeat ipsum.\nQuidem est illum.\nRepudiandae commodi eos quia sed saepe libero sint.\n \rMolestias id inventore dolores ullam enim voluptate nesciunt eligendi.\nIusto vero debitis animi dolorem eum.\nEt id repudiandae voluptas et voluptatem dignissimos.\nIpsum ullam quo modi voluptates quia molestias rem qui enim.\n \rExercitationem sit et dolor ullam error quam dolorem.\nFugiat rerum perferendis et quia tempora error illum.\nLaborum et soluta quia eligendi ut consequuntur accusantium.',
    imgURL: 'emo-black-male.png',
  },
  {
    id: 193054258,
    nationality: 'IT',
    keycardId: 'dbdc97c4-3887-41f3-bb80-f382c3470b8c',
    account: 'IT14 D927 8064 716N 2755 8B69 P69',
    salary: 1657,
    office: ['Torino', 'Italy'],
    departmentId: 6,
    firstName: 'Max',
    lastName: 'Piras',
    title: 'Junior Software Engineer',
    contractType: 'permanent',
    email: 'mapi@softix.it',
    hiredAt: '1990-03-29',
    expiresAt: '2017-06-28',
    personalInfo: {
      age: 64,
      phone: '1-858-224-0683 x82606',
      email: 'Max.Piras29@hotmail.com',
      address: {
        street: '70377 Thompson Canyon',
        city: 'Callie bury',
        country: 'Holy See (Vatican City State)',
      },
      dateOfBirth: '1954-04-25',
    },
    skills: [
      'Java',
      'JVM',
      'JSP',
      'Hibernate',
      'JavaScript',
      'react',
      'Angular',
      'jQuery',
      'CSS',
      'HTML',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Pariatur fuga consequuntur perferendis dolores.\nDolore qui ut minima deserunt.\nDolore ad debitis veritatis.\nPerspiciatis dolorum aut nihil ut optio adipisci et accusantium.\nMolestiae officia quae.\n \rEarum quas recusandae quo.\nDebitis qui quo voluptates numquam.\nSed rerum nam ut asperiores mollitia iure qui.\nOmnis sed culpa soluta adipisci placeat.\nMolestias consequatur soluta dolores alias sit quia consequuntur.\nPerferendis quae commodi hic sunt.\n \rUllam et reiciendis voluptatem.\nNeque ut qui.\nMaxime molestiae corporis eos natus voluptate laborum quibusdam harum.\nEnim omnis molestiae ratione illum.\nUnde debitis optio velit repellat necessitatibus explicabo illo excepturi.\nDucimus vel unde nihil et alias porro.',
    imgURL: 'superhero-black-panther-comics.png',
  },
  {
    id: 15309827,
    nationality: 'DE',
    keycardId: 'fac058af-a462-4037-a87f-8758b2a2c0aa',
    account: 'DE11 0090 8369 4180 0108 95',
    salary: 1495,
    office: ['München', 'Germany'],
    departmentId: 1,
    firstName: 'Kira',
    lastName: 'Jamrozy',
    title: 'Junior Java Engineer',
    contractType: 'contract',
    email: 'kija@softix.de',
    hiredAt: '2009-01-11',
    expiresAt: '2017-10-31',
    personalInfo: {
      age: 58,
      phone: '(080) 033-3379',
      email: 'Kira24@hotmail.com',
      address: {
        street: '729 Strosin Forge',
        city: 'Lake Valentina chester',
        country: 'Tunisia',
      },
      dateOfBirth: '1960-09-03',
    },
    skills: [
      'C#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'VisualStudio',
      'VSTS',
      'JavaScript',
      'redux',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'SOA',
      'MVC',
      'Security',
      'scrum',
      'testing',
    ],
    bio: 'Voluptatum sint officiis et itaque voluptas officia.\nAssumenda id quisquam laboriosam repudiandae a dolor consectetur accusamus.\nEst libero dolores praesentium consequatur nobis cupiditate ut.\nSed est dolores delectus fugiat.\nConsectetur vel eos voluptatem aut consequatur.\nBlanditiis laborum fugiat consectetur voluptas accusamus molestiae.\n \rFugit dolor deserunt vero nam et magni voluptas illum.\nIpsam et sit sint.\nQuod rerum accusantium deserunt unde voluptatibus.\nQui ut accusamus in voluptas nemo.\n \rVeniam rerum nesciunt officiis culpa ut et.\nSaepe officia qui quibusdam similique autem exercitationem voluptas quisquam esse.\nPlaceat alias ullam illo quaerat vel est ab.\nOfficia eius tenetur rerum enim adipisci.\nSint pariatur eos dolores aliquam sed consectetur.\nSuscipit et perspiciatis consectetur voluptas libero et mollitia.',
    imgURL: 'plumber-black-female.png',
  },
  {
    id: 2069658,
    nationality: 'PL',
    keycardId: 'e9f9c119-8d87-483d-8d98-8d8e1c45427a',
    account: 'PL88 8009 5043 4801 0721 2202 8006',
    salary: 6193,
    office: ['Łódź', 'Poland'],
    departmentId: 3,
    firstName: 'Zachary',
    lastName: 'Frączek',
    title: '.Net Engineer',
    contractType: 'contract',
    email: 'zafr@softix.com',
    hiredAt: '1998-11-05',
    expiresAt: '2019-03-28',
    personalInfo: {
      age: 59,
      phone: '461-045-5954',
      email: 'Zachary.Frczek12@hotmail.com',
      address: {
        street: '585 Corkery Pines',
        city: 'Jacobi mouth',
        country: 'Slovenia',
      },
      dateOfBirth: '1959-02-11',
    },
    skills: [
      'Java',
      'scala',
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'C#',
      'F#',
      '.net',
      'EntityFramework',
      'OData',
      'IIS',
      'Rx.net',
      'VisualStudio',
      'VSTS',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Fuga officiis iste non laboriosam et voluptas repellat.\nVitae odio molestias accusamus sint optio officia et quam modi.\nQuia fugiat omnis veritatis qui quia quia.\nEt sunt rerum illo nihil optio fugiat quisquam accusantium.\nSed doloribus officia aut et.\nQui eveniet dolor qui libero quas quis nihil.\n \rNihil repellendus qui.\nConsectetur culpa numquam dolorem dolor.\nQuis iusto ut sed.\n \rOfficia dolore qui esse aliquam sequi eius.\nSint qui eligendi voluptas rerum nisi esse ut.\nEt blanditiis quos reiciendis vel voluptatem qui eos dolores dolores.',
    imgURL: 'hipsters-asian-male.png',
  },
  {
    id: 406910533,
    nationality: 'PL',
    keycardId: '39ce45fa-3c62-4bd2-8814-a5366c9ca226',
    account: 'PL50 0001 5650 5270 0700 4201 0345',
    salary: 1847,
    office: ['Lublin', 'Poland'],
    departmentId: 5,
    firstName: 'Klaudiusz',
    lastName: 'Woś',
    title: 'Junior Software Developer',
    contractType: 'permanent',
    email: 'klwo@softix.com',
    hiredAt: '2008-10-14',
    expiresAt: '2018-12-16',
    personalInfo: {
      age: 47,
      phone: '(528) 172-9605',
      email: 'Klaudiusz56@hotmail.com',
      address: {
        street: '50198 Daisha Street',
        city: 'Grimes shire',
        country: 'Cook Islands',
      },
      dateOfBirth: '1971-10-28',
    },
    skills: [
      'JVM',
      'spring',
      'JSP',
      'Hibernate',
      'JavaScript',
      'TypeScript',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'scrum',
      'testing',
      'management',
    ],
    bio: 'Modi hic animi nesciunt iusto consequatur dolorem quia eos.\nQui eum totam consectetur labore maiores.\nAut laborum officiis culpa voluptatibus nisi.\nConsectetur est tenetur quas praesentium nulla iusto.\nFugiat enim similique est dolore voluptas non consequatur eligendi.\n \rQuas omnis impedit.\nEum asperiores et officia autem possimus repudiandae.\nNostrum expedita quo.\nSaepe nobis quaerat et nam tenetur qui.\n \rMinus et modi.\nQuibusdam voluptatem assumenda.\nEt maiores sunt.',
    imgURL: 'celebrity-barack-obama-president-potus.png',
  },
  {
    id: 23438716,
    nationality: 'US',
    keycardId: '8b75392b-2334-4c29-81f2-2593b4d18f49',
    account: 'US39 1069 1008 6601 0400 9726',
    salary: 3188,
    office: ['Dallas', 'United States of America'],
    departmentId: 2,
    firstName: 'Shawn',
    lastName: 'Sanford',
    title: 'Senior Big Data Engineer',
    contractType: 'permanent',
    email: 'shsa@softix.com',
    hiredAt: '1991-10-14',
    expiresAt: '2018-05-15',
    personalInfo: {
      age: 56,
      phone: '(451) 075-4079 x2421',
      email: 'Shawn_Sanford@hotmail.com',
      address: {
        street: '5822 Schowalter Loop',
        city: 'Rocio bury',
        country: 'Zambia',
      },
      dateOfBirth: '1962-03-13',
    },
    skills: ['Java', 'JVM', 'spring', 'Hibernate', 'sql'],
    bio: 'Magnam labore repudiandae eaque consequatur itaque consequatur molestias culpa.\nVoluptas et illum.\nOdit nesciunt et dolor eos a non aliquid sed.\nOmnis quia unde deserunt animi corrupti.\nEarum eum quo rem.\nEveniet sit quia rerum.\n \rAnimi est modi magni excepturi expedita doloribus quo qui.\nOmnis molestiae velit cum consequuntur ipsam qui.\nRepudiandae est rem tempora atque.\n \rEst et debitis ut nam temporibus error numquam.\nQuibusdam veritatis dignissimos ipsa animi error quia non voluptates a.\nQui enim animi modi maxime id molestiae.\nEt nemo autem rerum quod.',
    imgURL: 'aging-elderly-black-male.png',
  },
  {
    id: 3635045,
    nationality: 'US',
    keycardId: '18b6442c-ea39-425a-8528-081b23b68c6a',
    account: 'US63 0901 0059 1240 8445 0935',
    salary: 7471,
    office: ['Dallas', 'United States of America'],
    departmentId: 6,
    firstName: 'Otha',
    lastName: 'Wiegand',
    title: 'Big Data Engineer',
    contractType: 'contract',
    email: 'Otha.Wiegand@softix.us',
    hiredAt: '2000-04-12',
    expiresAt: '2018-05-06',
    personalInfo: {
      age: 27,
      phone: '(667) 599-5575 x20612',
      email: 'Otha_Wiegand@yahoo.com',
      address: {
        street: '077 Evan Mountain',
        city: 'Blanda ton',
        country: 'Dominica',
      },
      dateOfBirth: '1991-11-14',
    },
    skills: [
      'Java',
      'JVM',
      'Hibernate',
      'JavaScript',
      'CoffeeScript',
      'react',
      'AngularJS',
      'jQuery',
      'CSS',
      'HTML',
      'data structures',
      'scrum',
      'testing',
    ],
    bio: 'Neque ea voluptatem.\nQui aut molestiae recusandae magni id sit pariatur animi.\nSequi sit recusandae et.\nAnimi aut eveniet consequuntur.\n \rQui inventore provident dolore accusantium aliquam.\nPariatur aspernatur eum dolor aut sit.\nA qui voluptate voluptatem molestias facere possimus est.\n \rAdipisci fugit quo sunt.\nUt est dolor qui non provident molestias laborum sequi sit.\nMaxime aut repudiandae alias.',
    imgURL: 'private-investigator-white-female.png',
  },
  {
    id: 61610,
    nationality: 'PL',
    keycardId: 'ab1f82c2-b457-494d-8d90-e15b7c05f785',
    account: 'PL63 0800 3296 9139 0738 0048 8024',
    salary: 7326,
    office: ['Łódź', 'Poland'],
    departmentId: 3,
    firstName: 'Lucjan',
    lastName: 'Radecki',
    title: 'Senior Big Data Engineer',
    contractType: 'contract',
    email: 'Lucjan_Radecki@softix.com',
    hiredAt: '1998-06-11',
    expiresAt: '2018-07-12',
    personalInfo: {
      age: 24,
      phone: '881-977-2960 x803',
      email: 'Lucjan43@gmail.com',
      address: {
        street: '621 Aufderhar Parkway',
        city: 'Port Kayleigh view',
        country: 'Eritrea',
      },
      dateOfBirth: '1994-01-02',
    },
    skills: ['JavaScript', 'react', 'Angular', 'AngularJS', 'jQuery', 'HTML'],
    bio: 'Et ipsam et nisi laudantium porro magni nesciunt.\nAt inventore et temporibus qui.\nBlanditiis eos ipsa a voluptatem laudantium.\nLaborum corrupti possimus sit labore consequatur ipsum iure.\n \rIure voluptatem quisquam nisi occaecati sit assumenda blanditiis.\nId nesciunt ipsa facere vitae ullam eius.\nDeserunt in sequi quia.\nExcepturi occaecati in numquam.\n \rSuscipit esse assumenda ea et cum nam illum quaerat.\nSed illum voluptatem.\nVoluptas dolore officia incidunt est.\nVero vitae dolor debitis.',
    imgURL: 'doctor-asian-male.png',
  },
];
